### ISSUE TITLE
micro-infra-spring with JAX-RS

### ISSUE THREAD

**Issue by rtti** [4finance/boot-microservice#86]
Do we have possibility to send requests for services are not Spring but JAX-RS?

Rest service:

import javax.ws.rs.*;
@GET
@Path("patient/chart")
@Produces(MediaType.APPLICATION_JSON)
    public Response getSomething() {
            return Response.ok().build();
    }

and app config:

 ApplicationContext ctx = SpringApplication.run(MicroServiceConfig.class, args);

        ServiceRestClient serviceRestClient = (ServiceRestClient) ctx.getBean("serviceRestClient");
        String response = serviceRestClient.forService("main")
                .get()
                .onUrl("patient/chart")
                .anObject()
                .ofType(String.class);

        System.out.println(response);

Result fails with error:

com.ofg.infrastructure.web.resttemplate.custom.ResponseException: Status code: [404], Headers: [[Server:[Apache-Coyote/1.1], Content-Type:[application/json;charset=UTF-8], Transfer-Encoding:[chunked], Date:[Fri, 08 May 2015 09:56:47 GMT]]], Body: [{"timestamp":1431079007055,"status":404,"error":"Not Found","message":"No message available","path":"/patient/chart"}]

How can we use JAX-RS instead of Spring REST ?

**Comment by marcingrzejszczak** [comment]
Can you post your project on Gitub so that we can see your configuration?

**Comment by rtti** [comment]
Actually, I figured out hot it works :)
Now my problem is hot to sent request via ServiceRestClient to service which is defined on different port.

For example, I register service of ma first app (e.g. "UserService" with endpoint "/user/get") in ZooKeeper via @EnableServiceDiscovery and it is available on 
localhost:8080, and I have another app on localhost:8081 that needs "UserService".

I created 2 microservice.json : for the first  app and for second app. 

When I try to run 
serviceRestClient.forService("userService")
                .get()
                .onUrl("/user/get")
                .anObject()
                .ofType(String.class);

I got 404 , because of different port.
Could you tell me please, how can I solve this problem?

**Comment by marcingrzejszczak** [comment]
Hi Oleg,

I honestly don't understand this problem :p 

Let's assume that you have two services. 
- UserService (with endpoint /users/get - btw this is totally not a RESTful endpoint you know? :P ). It's running on a port 8080. Let's assume that in micro.json you have "this" as "/a/b/UserService"
- The other is SomeOtherService running on 8081. Let's assume that in micro.json you have "this" as "/a/b/SomeOtherService" .

Now, both of them registered in Zookeeper. If SomeOtherService needs to call UserService then it will you serviceRestClient just as you wrote. 

```
serviceRestClient.forService("userService")
.get()
.onUrl("/user/get")
.anObject()
.ofType(String.class);
```

That way under the hood a GET request via Spring's RestTEmplate will take place to localhost:8081/user/get . 

That means that's obvious that you need to have them on different ports if you are running it on a single machine.

BTW I strongly encourage you to write about this stuff on gitter: https://gitter.im/4finance/micro-infra-spring . That's because you're filling up issues that are not actually issues at all ;)

**Comment by rtti** [comment]
Thanks, I got it!
